### ISSUE TITLE
Bouton helloasso

### ISSUE THREAD

**Issue by priandey** [priandey/wantedvelo-front#27]
Submitter: joel
Insérer le bouton helloasso dans le bandeau Supérieur du site etou dans le.menu

**Comment by priandey** [comment]
- [ ] Vérifier si helloasso propose des intégrations
- [ ] Léger edit du frontend

**Comment by priandey** [comment]
- [ ] todo
- [

**Comment by priandey** [comment]
##Titre

**Comment by Joel-Colombes** [comment]
<iframe id="haWidget" allowtransparency="true" src="https://www.helloasso.com/associations/wanted-velo/adhesions/adhesion-wanted-velo/widget-bouton" style="width:100%;height:70px;border:none;"></iframe><div style="width:100%;text-align:center;">Propulsé par <a href="https://www.helloasso.com" rel="nofollow">HelloAsso</a></div>

**Comment by priandey** [comment]
`<iframe id="haWidget" allowtransparency="true" src="https://www.helloasso.com/associations/wanted-velo/adhesions/adhesion-wanted-velo/widget-bouton" style="width:100%;height:70px;border:none;"></iframe>`

**Comment by priandey** [comment]
L'intégrer suite à une action engageante de la part de l'utilisateur (déclaration de vol, réception d'une alerte, etc.)
